Repository sussinbussin/bussin-SpringBack, pull requests merged in 2022-10, with the labels that each got.

#37 Made filtering more specific
  src/main/java/com/bussin/SpringBack/security/SecurityConfiguration.java
Labels: enhancement

#38 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#39 check passenger count when creating new ride
  src/main/java/com/bussin/SpringBack/controllers/ExceptionHandling.java
  src/main/java/com/bussin/SpringBack/exception/RideException.java
  src/main/java/com/bussin/SpringBack/services/RideService.java
  src/test/java/com/bussin/SpringBack/rideTests/RideIntegrationTests.java
  src/test/java/com/bussin/SpringBack/rideTests/RideServiceTests.java
Labels: enhancement

#41 Added schema descriptions and examples
  src/main/java/com/bussin/SpringBack/models/Driver.java
  src/main/java/com/bussin/SpringBack/models/DriverDTO.java
  src/main/java/com/bussin/SpringBack/models/PlannedRoute.java
  src/main/java/com/bussin/SpringBack/models/PlannedRouteDTO.java
  src/main/java/com/bussin/SpringBack/models/Ride.java
  src/main/java/com/bussin/SpringBack/models/RideCreationDTO.java
  src/main/java/com/bussin/SpringBack/models/RideDTO.java
  src/main/java/com/bussin/SpringBack/models/User.java
  src/main/java/com/bussin/SpringBack/models/UserDTO.java
Labels: documentation

#43 Bugs/jwt verification exception fix
  src/main/java/com/bussin/SpringBack/controllers/ExceptionHandling.java
  src/main/java/com/bussin/SpringBack/security/TokenValidator.java
  src/test/java/com/bussin/SpringBack/plannedRouteTests/PlannedRouteIntegrationTests.java
  src/test/java/com/bussin/SpringBack/userTests/UserIntegrationTests.java
Labels: bug

#42 added one more userintegrationtests
  src/test/java/com/bussin/SpringBack/userTests/UserIntegrationTests.java
Labels: enhancement

#44 Feature/signup with cognito
  .github/workflows/maven.yml
  pom.xml
  src/main/java/com/bussin/SpringBack/config/CognitoConfig.java
  src/main/java/com/bussin/SpringBack/controllers/UserController.java
  src/main/java/com/bussin/SpringBack/integrationTestAuth/CognitoLogin.java
  src/main/java/com/bussin/SpringBack/models/UserCreationDTO.java
  src/main/java/com/bussin/SpringBack/security/SecurityConfiguration.java
  src/main/java/com/bussin/SpringBack/services/UserService.java
  src/main/resources/application.properties
  src/test/java/com/bussin/SpringBack/driverTests/DriverServiceTests.java
  src/test/java/com/bussin/SpringBack/securityTests/RouteSecurityTests.java
  src/test/java/com/bussin/SpringBack/userTests/UserServiceTests.java
  src/test/resources/application.properties
Labels: enhancement

#60 Coveralls and readme
  .github/workflows/maven.yml
  README.md
  pom.xml
Labels: documentation

#61 CognitoUserTests and Refactoring
  README.md
  src/main/java/com/bussin/SpringBack/exception/CannotConnectException.java
  src/main/java/com/bussin/SpringBack/exception/CannotConnectToDistanceServerException.java
  src/main/java/com/bussin/SpringBack/exception/DriverNotFoundException.java
  src/main/java/com/bussin/SpringBack/exception/PlannedRouteNotFoundException.java
  src/main/java/com/bussin/SpringBack/exception/RideException.java
  src/main/java/com/bussin/SpringBack/exception/RideNotFoundException.java
  src/main/java/com/bussin/SpringBack/exception/UserNotFoundException.java
  src/main/java/com/bussin/SpringBack/exception/WrongUserException.java
  src/main/java/com/bussin/SpringBack/integrationTestAuth/CognitoLogin.java
  src/main/java/com/bussin/SpringBack/models/UserCreationDTO.java
  src/main/java/com/bussin/SpringBack/services/PlannedRouteService.java
  src/test/java/com/bussin/SpringBack/TestObjects.java
  src/test/java/com/bussin/SpringBack/userTests/UserCognitoTests.java
  src/test/java/com/bussin/SpringBack/userTests/UserServiceTests.java
Labels: documentation, enhancement

#62 Removed unused route and methods
  src/main/java/com/bussin/SpringBack/controllers/ExceptionHandling.java
  src/main/java/com/bussin/SpringBack/controllers/PlannedRouteController.java
  src/main/java/com/bussin/SpringBack/exception/CannotConnectToDistanceServerException.java
  src/main/java/com/bussin/SpringBack/services/PlannedRouteService.java
Labels: enhancement
